"""Build the per-sheet calculation inventory for excel-navigator.

Reads an extract.json (schema: ../_excel-shared/references/extraction_guide.md)
and, for every sheet that contains formulas, walks each formula row and emits:

    Row | Label | Cells | Dominant R1C1 | Sample (A1) | Patterns

- Label        = nearest text to the LEFT of the row's first formula cell
                 (from text_inventory) — usually the row description.
- Cells        = grouped span of the row's formula cells (audit_lib grouping).
- Dominant R1C1 = the row's most common R1C1 signature (from r1c1_rows).
- Sample (A1)  = the A1 formula of the dominant pattern's first cell.
- Patterns     = number of distinct R1C1 signatures in the row; more than one
                 marks a break candidate worth a closer look while documenting.

A sheet-flow summary (cross-sheet formula edges in data-flow direction) opens
the document, and each sheet section notes what it reads from and feeds.

This is the deterministic skeleton for the NAV_03 Calculation Reference.
Claude's judgment pass adds the plain-English Readable Formula column per
references/calc_reference_syntax.md — translation needs label comprehension,
which no script has.

Usage:
    python build_calc_inventory.py <extract.json> [--out OUT|-]

Default output is stdout. Exit code 0 on success.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "_excel-shared" / "scripts"))
from audit_lib import load_extract, parse_a1, cells_to_ranges  # noqa: E402


def _esc(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _code(text: str) -> str:
    return "`" + _esc(text) + "`" if text else ""


def text_map(extract: dict, sheet: str) -> dict[tuple[int, int], str]:
    """{(row, col): text} for every constant string on the sheet."""
    out: dict[tuple[int, int], str] = {}
    for rec in extract.get("text_inventory", {}).get(sheet, []):
        try:
            out[parse_a1(rec["addr"])] = rec["text"]
        except ValueError:
            continue
    return out


def nearest_left_label(texts: dict[tuple[int, int], str], row: int, before_col: int) -> str:
    """Closest text cell left of the first formula cell in the same row."""
    candidates = [(c, t) for (r, c), t in texts.items() if r == row and c < before_col]
    return max(candidates)[1] if candidates else "(no label)"


def row_patterns(extract: dict, sheet: str, row: int, recs: list[dict]) -> dict[str, list[str]]:
    """R1C1 signature -> [addresses], preferring the extractor's pre-compute."""
    for entry in extract.get("r1c1_rows", {}).get(sheet, []):
        if entry.get("row") == row:
            return entry.get("patterns", {})
    patterns: dict[str, list[str]] = {}
    for rec in recs:
        sig = rec.get("r1c1", rec.get("f", ""))
        patterns.setdefault(sig, []).append(rec["addr"])
    return patterns


def sheet_flow_table(extract: dict) -> list[str]:
    edges = extract.get("dependencies", {}).get("sheet_edges", [])
    if not edges:
        return ["No cross-sheet formula references found."]
    lines = ["| Source sheet | Feeds | Refs |", "|---|---|---|"]
    # extract.json edges run referencing -> referenced; flip to data-flow order.
    for e in sorted(edges, key=lambda e: (-e.get("count", 0), e["to"], e["from"])):
        lines.append(f"| {_esc(e['to'])} | {_esc(e['from'])} | {e.get('count', 1)} |")
    return lines


def sheet_flow_note(extract: dict, sheet: str) -> str:
    edges = extract.get("dependencies", {}).get("sheet_edges", [])
    reads = [f"{e['to']} ({e.get('count', 1)} refs)" for e in edges if e["from"] == sheet]
    feeds = [f"{e['from']} ({e.get('count', 1)} refs)" for e in edges if e["to"] == sheet]
    parts = []
    if reads:
        parts.append("Reads from: " + ", ".join(reads) + ".")
    if feeds:
        parts.append("Feeds: " + ", ".join(feeds) + ".")
    return " ".join(parts) or "No cross-sheet formula links."


def build_inventory(extract: dict) -> str:
    lines = [
        "# Calculation Inventory — deterministic skeleton",
        "",
        "Generated by `build_calc_inventory.py`. One row per formula row.",
        "Judgment pass pending: add the plain-English Readable Formula column",
        "per `references/calc_reference_syntax.md`.",
        "",
        "## Sheet flow (cross-sheet formula references, data-flow direction)",
        "",
    ]
    lines += sheet_flow_table(extract)

    total_rows = 0
    for sheet_meta in extract["meta"]["sheets"]:
        sheet = sheet_meta["name"]
        recs = [r for r in extract.get("cells", {}).get(sheet, []) if "f" in r]
        if not recs:
            continue
        rows: dict[int, list[dict]] = {}
        for rec in recs:
            rows.setdefault(rec["r"], []).append(rec)
        texts = text_map(extract, sheet)

        hidden = " 🙈 (hidden)" if sheet_meta.get("state", "visible") != "visible" else ""
        lines += ["", f"## {sheet}{hidden} ({len(rows)} formula rows)", "",
                  sheet_flow_note(extract, sheet), "",
                  "| Row | Label | Cells | Dominant R1C1 | Sample (A1) | Patterns |",
                  "|---|---|---|---|---|---|"]

        for row in sorted(rows):
            row_recs = sorted(rows[row], key=lambda r: r["c"])
            patterns = row_patterns(extract, sheet, row, row_recs)
            # Dominant = most cells; ties broken by leftmost first address.
            by_addr = {a: rec for rec in row_recs for a in [rec["addr"]]}
            dom_sig, dom_addrs = max(
                patterns.items(),
                key=lambda kv: (len(kv[1]),
                                -min((parse_a1(a)[1] for a in kv[1]), default=0)),
            )
            dom_addrs = sorted(dom_addrs, key=lambda a: parse_a1(a))
            sample_rec = by_addr.get(dom_addrs[0]) if dom_addrs else None
            sample = sample_rec.get("f", "") if sample_rec else ""
            span = cells_to_ranges({(rec["r"], rec["c"]) for rec in row_recs})
            label = nearest_left_label(texts, row, row_recs[0]["c"])
            n_pat = len(patterns)
            pat_note = str(n_pat) if n_pat == 1 else f"{n_pat} — break candidate"
            lines.append(
                f"| {row} | {_esc(label)} | {span} | {_code(dom_sig)} "
                f"| {_code(sample)} | {pat_note} |"
            )
            total_rows += 1

    lines += ["", f"_{total_rows} formula rows documented across the workbook._", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("extract", help="Path to extract.json")
    ap.add_argument("--out", help="Output path ('-' or omitted = stdout)")
    args = ap.parse_args(argv)

    inventory = build_inventory(load_extract(args.extract))
    if args.out and args.out != "-":
        path = Path(args.out)
        if path.parent != Path("."):
            path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(inventory, encoding="utf-8")
        print(f"Wrote calculation inventory -> {args.out}")
    else:
        print(inventory)
    return 0


if __name__ == "__main__":
    sys.exit(main())
